Add collection typedef
korfuri/client_cpp pull request #12
Opened 2016-10-02 16:31 UTC by agnat

In preparation of implementing the binary output format `application/vnd.google.protobuf` I'd like to land this little clean-up.

2016-10-03 00:34 UTC, korfuri requested changes
Look good overall, thanks!
Please rebase as right now there are some merge conflicts :)

2016-10-03 00:34 UTC, korfuri commented on prometheus/registry.hh
> +      typedef Collector::collection_type collection_type;
Is there a specific reason you're re-typedefing here instead of using `using` statements?

2016-10-03 03:42 UTC, agnat commented on prometheus/registry.hh
> +      typedef Collector::collection_type collection_type;
Old habits die hard. Will update.

2016-10-03 03:54 UTC, agnat commented
Done.

2016-10-03 22:33 UTC, agnat commented
Depends on #14.

2016-10-05 23:53 UTC, korfuri approved these changes

2016-10-05 23:53 UTC, merged